version: "3.9"

services:
  fastapi-todolist:
    build: .
    container_name: fastapi-todolist
    ports:
      - "8000:8000"
    depends_on:
      - mysql-dev
      - redis-dev
    restart: always
    environment:
      - DATABASE_HOST=mysql-dev
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mysql-dev:
    image: mysql:8.0
    container_name: mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_db
      MYSQL_USER: gustavo
      MYSQL_PASSWORD: teste
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-dev:
    image: redis:7.2
    container_name: redis-dev
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
